spring.application.name=roommanagement

# Database - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/roommanagement_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=rra_meeting_room_secret_key_2024_very_long_secret_for_hs256
jwt.expiration=86400000

# Server
server.port=8080

# CORS
spring.web.cors.allowed-origins=http://localhost:3000
